### ISSUE TITLE
Помоги 

### ISSUE THREAD

**Issue by Diseerr** [Fequme/Economy-bot-discord#4]
Привет, у тебя бот не запускается, можешь ли как-то помочь?

**Comment by kbrddestroyer** [comment]
Скорее всего проблема в неразрешенных импортах. Нужно установить зависимости, так как нет requirements.txt делать это придется вручную. 

`pip install python-dotenv`
`pip install -U discord.py`

**Comment by Diseerr** [comment]
> Скорее всего проблема в неразрешенных импортах. Нужно установить зависимости, так как нет requirements.txt делать это придется вручную.
> 
> `pip install python-dotenv` `pip install -U discord.py`

Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\bot.py", line 11, in <module>
    from modules.Marry import Marry
  File "c:\Users\corny\Desktop\Economy\modules\Marry.py", line 2, in <module>
    from discord import Option
ImportError: cannot import name 'Option' from 'discord' (C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\__init__.py)

**Comment by kbrddestroyer** [comment]
> > Скорее всего проблема в неразрешенных импортах. Нужно установить зависимости, так как нет requirements.txt делать это придется вручную.
> > 
> > `pip install python-dotenv` `pip install -U discord.py`
> 
> Traceback (most recent call last):
>   File "c:\Users\corny\Desktop\Economy\bot.py", line 11, in <module>
>     from modules.Marry import Marry
>   File "c:\Users\corny\Desktop\Economy\modules\Marry.py", line 2, in <module>
>     from discord import Option
> ImportError: cannot import name 'Option' from 'discord' (C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\__init__.py)

https://stackoverflow.com/questions/73464299/importerror-cannot-import-name-option-from-discord

Скорее всего что-то конфликтует в библиотеках, попробуй переустановить discord.py (шаги описаны в приложенном вопросе на StackOverflow). Если проблема сохранится - пингуй

**Comment by Diseerr** [comment]
> > > Скорее всего проблема в неразрешенных импортах. Нужно установить зависимости, так как нет requirements.txt делать это придется вручную.
> > > `pip install python-dotenv` `pip install -U discord.py`
> > 
> > 
> > Traceback (most recent call last):
> > File "c:\Users\corny\Desktop\Economy\bot.py", line 11, in 
> > from modules.Marry import Marry
> > File "c:\Users\corny\Desktop\Economy\modules\Marry.py", line 2, in 
> > from discord import Option
> > ImportError: cannot import name 'Option' from 'discord' (C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord__init__.py)
> 
> https://stackoverflow.com/questions/73464299/importerror-cannot-import-name-option-from-discord
> 
> Скорее всего что-то конфликтует в библиотеках, попробуй переустановить discord.py (шаги описаны в приложенном вопросе на StackOverflow). Если проблема сохранится - пингуй

Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 138, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 1078, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "c:\Users\corny\Desktop\Economy\modules\Shop.py", line 61, in shop
    roles = self.db.get_shop_roles()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\corny\Desktop\Economy\modules\Database.py", line 552, in get_shop_roles
    for row in self.cursor.execute(f"SELECT * FROM shop"):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\client.py", line 412, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\corny\Desktop\Economy\modules\Economy.py", line 60, in on_application_command_error
    raise error
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\bot.py", line 1137, in invoke_application_command    
    await ctx.command.invoke(ctx)
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 435, in invoke
    await injected(ctx)
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 146, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: OperationalError: no such table: shop

**Comment by Diseerr** [comment]
Ignoring exception in modal <modules.AdminPanel.AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_rooms.<locals>.ButtonsManipulateRooms.button_callback_balance_give.<locals>.RoomCreateModal object at 0x000001FBBAD6AC90>:
Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ui\modal.py", line 341, in dispatch
    await value.callback(interaction)
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 228, in callback
    globalself.db.write_new_personal_room(member, self.children[0].value)
  File "c:\Users\corny\Desktop\Economy\modules\Database.py", line 590, in write_new_personal_room
    self.cursor.execute(f"INSERT INTO personal_rooms VALUES (?, ?, ?, ?, ?, ?)", (member.id, '[]', '[]', name, '0', int(datetime.now().timestamp()),))
sqlite3.OperationalError: no such table: personal_rooms
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-9455227376743dbdb1e37ce08d99504d' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_balance.<locals>.ButtonsManipulateBalance.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:71> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 72, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-e3ad7c817d44c38bfa8a223c6bbfda11' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_balance.<locals>.ButtonsManipulateBalance.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:71> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 72, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-367eba318fa13f2b0947198b6ea95108' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_rooms.<locals>.ButtonsManipulateRooms.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:200> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 201, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

**Comment by Diseerr** [comment]
> > > Скорее всего проблема в неразрешенных импортах. Нужно установить зависимости, так как нет requirements.txt делать это придется вручную.
> > > `pip install python-dotenv` `pip install -U discord.py`
> > 
> > 
> > Traceback (most recent call last):
> > File "c:\Users\corny\Desktop\Economy\bot.py", line 11, in 
> > from modules.Marry import Marry
> > File "c:\Users\corny\Desktop\Economy\modules\Marry.py", line 2, in 
> > from discord import Option
> > ImportError: cannot import name 'Option' from 'discord' (C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord__init__.py)
> 
> https://stackoverflow.com/questions/73464299/importerror-cannot-import-name-option-from-discord
> 
> Скорее всего что-то конфликтует в библиотеках, попробуй переустановить discord.py (шаги описаны в приложенном вопросе на StackOverflow). Если проблема сохранится - пингуй

Ignoring exception in on_application_command_error
Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 138, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 1078, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "c:\Users\corny\Desktop\Economy\modules\Shop.py", line 61, in shop
    roles = self.db.get_shop_roles()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\corny\Desktop\Economy\modules\Database.py", line 552, in get_shop_roles
    for row in self.cursor.execute(f"SELECT * FROM shop"):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: shop

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\client.py", line 412, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\corny\Desktop\Economy\modules\Economy.py", line 60, in on_application_command_error
    raise error
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\bot.py", line 1137, in invoke_application_command    
    await ctx.command.invoke(ctx)
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 435, in invoke
    await injected(ctx)
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\commands\core.py", line 146, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: OperationalError: no such table: shop
Ignoring exception in modal <modules.AdminPanel.AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_rooms.<locals>.ButtonsManipulateRooms.button_callback_balance_give.<locals>.RoomCreateModal object at 0x000001FBBAD6AC90>:
Traceback (most recent call last):
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ui\modal.py", line 341, in dispatch
    await value.callback(interaction)
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 228, in callback
    globalself.db.write_new_personal_room(member, self.children[0].value)
  File "c:\Users\corny\Desktop\Economy\modules\Database.py", line 590, in write_new_personal_room
    self.cursor.execute(f"INSERT INTO personal_rooms VALUES (?, ?, ?, ?, ?, ?)", (member.id, '[]', '[]', name, '0', int(datetime.now().timestamp()),))
sqlite3.OperationalError: no such table: personal_rooms
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-9455227376743dbdb1e37ce08d99504d' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_balance.<locals>.ButtonsManipulateBalance.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:71> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 72, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-e3ad7c817d44c38bfa8a223c6bbfda11' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_balance.<locals>.ButtonsManipulateBalance.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:71> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 72, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
Task exception was never retrieved
future: <Task finished name='discord-ui-view-timeout-367eba318fa13f2b0947198b6ea95108' coro=<AdminPanel.casino.<locals>.ButtonsManipulate.button_callback_manipulate_rooms.<locals>.ButtonsManipulateRooms.on_timeout() done, defined at c:\Users\corny\Desktop\Economy\modules\AdminPanel.py:200> exception=NotFound('404 Not Found (error code: 10008): Unknown Message')>
Traceback (most recent call last):
  File "c:\Users\corny\Desktop\Economy\modules\AdminPanel.py", line 201, in on_timeout
    await ctx.edit(view=View())
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 513, in edit_original_response    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\corny\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 222, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

**Comment by kbrddestroyer** [comment]
Судя по трейсу у тебя как минимум не развёрнута база данных, либо в ней отсутствуют некоторые таблицы (видно ошибку в SELECT запросе no such table), насчёт установки я думаю у автора должен быть гайд или скрипты

**Comment by Diseerr** [comment]
> Судя по трейсу у тебя как минимум не развёрнута база данных, либо в ней отсутствуют некоторые таблицы (видно ошибку в SELECT запросе no such table), насчёт установки я думаю у автора должен быть гайд или скрипты

А что делать если нету?, и я хотел у тебя спросить у тебя есть этот код но полностью исправен?

**Comment by Diseerr** [comment]
И вообще спасибо что помогаешь

**Comment by kbrddestroyer** [comment]
> А что делать если нету?

Надо разворачивать, MySQL позволяет установить СУБД локально, в нем можно разместить требуемую схему.

> и я хотел у тебя спросить у тебя есть этот код но полностью исправен?

Я хотел сделать форк для того чтобы вносить изменения, но у автора есть более новая версия бота в другом репозитории. Если и буду этим заниматься то скорее всего там

**Comment by Diseerr** [comment]
> > А что делать если нету?
> 
> Надо разворачивать, MySQL позволяет установить СУБД локально, в нем можно разместить требуемую схему.
> 
> > и я хотел у тебя спросить у тебя есть этот код но полностью исправен?
> 
> Я хотел сделать форк для того чтобы вносить изменения, но у автора есть более новая версия бота в другом репозитории. Если и буду этим заниматься то скорее всего там

ты можешь свой дискорд скинуть?

**Comment by kbrddestroyer** [comment]
https://discordapp.com/users/501398423329701889

Или

https://discord.gg/9mG2vAsyet

**Comment by kbrddestroyer** [comment]
@Fequme можно закрыть Issue
